version: '3.8'

services:

  app:
    build: .
    container_name: my-tiny-url-app
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    restart: unless-stopped


  postgres:
    container_name: my-tiny-url-postgres
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: unless-stopped


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge